web/app/component/mqtt.go
Signed-off-by: yanghua <yanghua1127@gmail.com>
=> #25 go vet failure

web/static/css/main.css, web/static/index.html, web/static/js/main.js
Signed-off-by: xiefayang <coderthank@163.com>
=> #9improve menu

web/static/css/main.css, web/static/data/menu.json
Signed-off-by: xiefayang <coderthank@163.com>
=> #34Update menu.json, adding Log,Nofification,Scheduler module

web/static/css/devices/device.css, web/static/css/devices/deviceService.css
=> supplement all css for device and device service

web/static/css/logging.css, web/static/js/logging.js, web/static/pages/logging.html
=> issue#10 improve logging with realtime output

web/static/css/notification.css, web/static/js/notification.js, web/static/pages/notification.html
=> issue#11 add notification module

web/static/js/pages/devices/deviceService.js
Signed-off-by: thank037 <coderthank@163.com>
=> fix issue #55

web/static/js/pages/ruleengine.js, web/static/pages/ruleengine.html
=> issue-#57 ruleengine improved using panel wrapper

web/static/js/pages/devices/deviceService.js
=> fix issue-#71 bug

cmd/edgex-ui-server/static/js/pages/devices/deviceService.js, cmd/edgex-ui-server/static/pages/devices/deviceService.html, go.mod
Finish issue-#86 Refactor device address form
=> Finish issue-#86 Refactor device address form

app/repository/mm/gateway.go
=> Fix issue-#92 remove gateway data when click delete button

Dockerfile, cmd/edgex-ui-server/static/js/pages/devices/deviceService.js
Finish issue-#82 about Docker build image without source code
=> Finish issue-#82 about Docker build image without source code

cmd/edgex-ui-server/static/js/pages/devices/deviceService.js
=> Fix issue#76

cmd/edgex-ui-server/static/js/pages/devices/deviceService.js, cmd/edgex-ui-server/static/pages/devices/deviceService.html
=> Fix issue#78

cmd/edgex-ui-server/static/js/pages/logging.js, cmd/edgex-ui-server/static/pages/logging.html
=> add all micro service dynamically and add erase screen btn

cmd/edgex-ui-server/static/js/pages/scheduler.js, cmd/edgex-ui-server/static/pages/scheduler.html
=> Fix issue-#101

cmd/edgex-ui-server/static/js/pages/scheduler.js, cmd/edgex-ui-server/static/pages/scheduler.html
=> Fix bug issue-#103

cmd/edgex-ui-server/static/js/pages/notification.js, cmd/edgex-ui-server/static/pages/notification.html
=> Fix issue-#105

README.md
Add project structure description
=> Add project structure description

.gitignore, snap/hooks/install, snap/local/runtime-helpers/bin/edgex-ui-wrapper.sh, snap/snapcraft.yaml
Backport of #112 to Edinburgh branch
=> Add Edinburgh snap

app/component/websocket.go
=> Fix issue-#109

app/repository/mongo/mongo.go
add function loadConf to defer variable assignment, hence configuration variable should be loaded at the first place.
=> Deffered variable assignment to fix #127

app/common/filter.go, cmd/edgex-ui-server/main.go, go.mod, internal/pkg/usage/usage.go
Fix #111
Signed-off-by: Jason Bonafide <jbonafide623@gmail.com>
=> Add command line option to specify configuration.toml location

app/configs/configuration.go, app/controller/appservice.go, app/router.go, cmd/edgex-ui-server/res/configuration.toml, cmd/edgex-ui-server/res/docker/configuration.toml, go.mod
Github issue #147. @badboy-huaqiao
=> [enhancement] Add app service builder api

cmd/edgex-ui-server/static/css/appService.css, cmd/edgex-ui-server/static/data/menu.json, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
Add AppService new page, to support App-service-configurable and SDK.
=> add new page AppServices

cmd/edgex-ui-server/static/css/appService.css, cmd/edgex-ui-server/static/data/menu.json, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
=> Issue #153

cmd/edgex-ui-server/static/js/edgexfoundry.js, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
=> [enhancement] add Pipeline FunctionList and use block-level scoping

cmd/edgex-ui-server/static/css/appService.css, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
issue #154 , @badboy-huaqiao please review ,Thank you.
=> add folder to type of Functions

cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
issue #156 , @badboy-huaqiao please review this code, thank you
=> download profile function finish

cmd/edgex-ui-server/static/js/pages/devices/deviceService.js, cmd/edgex-ui-server/static/pages/devices/deviceService.html
Signed-off-by: zhanglibin <zlibin@vmware.com> @badboy-huaqiao
=> Issue #151

cmd/edgex-ui-server/static/js/pages/devices/deviceService.js, cmd/edgex-ui-server/static/pages/devices/deviceService.html
to render user response message by status code
issue #163
=> Change form submit to ajax way when upload device profile

cmd/edgex-ui-server/static/css/appService.css, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
issue #155 , @badboy-huaqiao ,please review the code,thank you.
=> use dialog to input params

cmd/edgex-ui-server/static/js/pages/appService.js
=> Test to deploy profile to consul and fix bug

cmd/edgex-ui-server/static/css/appService.css, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
issue #157 , @badboy-huaqiao please review and merge this pr ,thank you.
=> deploy button finished

cmd/edgex-ui-server/static/js/common.js, cmd/edgex-ui-server/static/js/pages/devices/deviceService.js, cmd/edgex-ui-server/static/js/pages/scheduler.js, cmd/edgex-ui-server/static/pages/scheduler.html
=> Update Interval part in scheduler page to match edgexfoundry

cmd/edgex-ui-server/static/js/common.js, cmd/edgex-ui-server/static/js/pages/scheduler.js, cmd/edgex-ui-server/static/pages/scheduler.html
=> Update interval action(ScheduleEvent) ui part

cmd/edgex-ui-server/static/css/appService.css, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
issue #174 ,please review my code ,thanks .@badboy-huaqiao
=> modify some code,and deploy validate

cmd/edgex-ui-server/static/js/pages/notification.js, cmd/edgex-ui-server/static/pages/notification.html
1> add non-empty judgment for query startTime and endTime
2> modify ajax response for rendering front page when happened error.
issue #178
@badboy-huaqiao #178
=> Modify condition query for notification list

cmd/edgex-ui-server/static/data/menu.json, cmd/edgex-ui-server/static/js/pages/appService.js
=> hide the logging page menu ,and modify appservice

app/configs/configuration.go, app/controller/appservice.go, app/router.go, cmd/edgex-ui-server/res/configuration.toml, cmd/edgex-ui-server/res/docker/configuration.toml
=> add query appservice config list api

app/controller/errors/types.go, app/controller/gateway.go, cmd/edgex-ui-server/static/js/pages/gateway.js
=> Add parameters vertification for gateway page

app/controller/appservice.go
=> Fix path separator problem on Windows

Dockerfile, cmd/edgex-ui-server/res/docker/configuration.toml
Issue #190
#190  @badboy-huaqiao  @rsdmike
=> fix for configuration.toml not using the correct configuration

Dockerfile, go.mod
=> update go version to 1.13

cmd/edgex-ui-server/static/js/main.js, cmd/edgex-ui-server/static/js/pages/gateway.js, internal/handler/appservice.go, internal/router.go
=> [feat] Add edgex services alive check

cmd/edgex-ui-server/static/js/common.js, cmd/edgex-ui-server/static/js/pages/gateway.js, cmd/edgex-ui-server/static/js/pages/scheduler.js
=> [fix] fix utc date conversion bug for scheduler datetime

cmd/edgex-ui-server/static/css/devices/deviceService.css, cmd/edgex-ui-server/static/js/pages/devices/deviceService.js
=> [feat] Add css style for deviceService page

cmd/edgex-ui-server/static/css/appService.css, cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html
issue #186 ,@badboy-huaqiao ,please review,thank you.
=> app service page bug fix

README.md
=> Sync doc for EdgeX Geneva UI

cmd/edgex-ui-server/res/docker/configuration.toml
=> Modify Registry Host value to localhost in docker configuration way

.gitignore, cmd/edgex-ui-server/res/docker/configuration.toml
=> Use container name to access EdgeX in the docker configuration way

README.md
modify README.md ,to add video link .
=> add video link in README

go.mod, internal/configs/config.go, internal/configs/environment.go
=> [feat] Add override environment support

cmd/edgex-ui-server/static/js/pages/notification.js
=> Remove useless code about gateway messbox prompt

README.md, cmd/edgex-ui-server/static/css/index.css, cmd/edgex-ui-server/static/index.html, internal/core/filter.go
Block user login and user create page, and add note in Readme.md
=> block user login and user create page

cmd/edgex-ui-server/static/js/pages/appService.js, cmd/edgex-ui-server/static/pages/appService.html, internal/handler/appservice.go, internal/router.go
add receiver in app service page issue:#215. please review, thanks.
=> add receiver in app service page

README.md, cmd/edgex-ui-server/static/css/ruleengine.css, cmd/edgex-ui-server/static/data/menu.json, cmd/edgex-ui-server/static/index.html, cmd/edgex-ui-server/static/js/main.js, cmd/edgex-ui-server/static/js/pages/devices/deviceService.js, cmd/edgex-ui-server/static/js/pages/ruleengine.js, cmd/edgex-ui-server/static/pages/appService.html, cmd/edgex-ui-server/static/pages/ruleengine.html, cmd/edgex-ui-server/static/vendors/json-viewer/css/jquery.json-viewer.css, cmd/edgex-ui-server/static/vendors/json-viewer/js/jquery.json-viewer.js
What kind of change does this PR introduce?
Issue Number: #218 
yes, new module is the new rule engine for support Kuiper.
none
=> Issue #218

cmd/edgex-ui-server/static/css/notification.css, cmd/edgex-ui-server/static/js/pages/notification.js, cmd/edgex-ui-server/static/pages/notification.html
What kind of change does this PR introduce?
Issue Number:
#257 
no
no
no
=> clean up notifications

cmd/edgex-ui-server/static/css/notification.css, cmd/edgex-ui-server/static/js/pages/notification.js, cmd/edgex-ui-server/static/pages/notification.html
What kind of change does this PR introduce?
Issue Number:
#257 
no
=> Issue #257

cmd/edgex-ui-server/static/js/common.js
=> fix the date bug

cmd/edgex-ui-server/static/js/main.js
=> modify rule engine health check

README.md
=> deployment description

cmd/edgex-ui-server/static/css/coreDataView.css, cmd/edgex-ui-server/static/data/menu.json, cmd/edgex-ui-server/static/js/common.js, cmd/edgex-ui-server/static/js/pages/coreDataView.js, cmd/edgex-ui-server/static/pages/coreDataView.html
=> core data view page complete

cmd/edgex-ui-server/static/css/realTimeDataView.css, cmd/edgex-ui-server/static/data/menu.json, cmd/edgex-ui-server/static/js/pages/coreDataView.js, cmd/edgex-ui-server/static/js/pages/realTimeDataView.js, cmd/edgex-ui-server/static/pages/realTimeDataView.html
=> add realtime data page

internal/handler/appservice.go
remove all register method for new version API v2 in furture
remove all register method for new version API v2 in furture
- [* ] No
- [* ] No
=> remove all register method for new version API v2 in furture

web/src/app/device-service/device/add-device/add-device.component.html, web/src/app/device-service/device/add-device/add-device.component.ts, web/src/app/device-service/device/edit-device/edit-device.component.html, web/src/app/device-service/device/edit-device/edit-device.component.ts, web/src/app/device-service/profile/device-profile-list/device-profile-list.component.html, web/src/app/device-service/profile/device-profile-list/device-profile-list.component.ts, web/src/app/services/metadata.service.ts
#275
deviceprofle list component refactor
- [* ] No
- [ *] No
=> feat: Issue #275 deviceprofle list component refactor

web/src/app/contracts/kuiper/options.ts, web/src/app/contracts/kuiper/rule.ts, web/src/app/contracts/kuiper/stream-fields.ts, web/src/app/contracts/kuiper/stream-options.ts, web/src/app/contracts/kuiper/stream.ts, web/src/app/rule-engine/rules/add-rules/add-rules.component.ts, web/src/app/rule-engine/rules/edit-rules/edit-rules.component.ts, web/src/app/rule-engine/rules/rules-list/rules-list.component.ts, web/src/app/rule-engine/stream/edit-stream/edit-stream.component.ts, web/src/app/rule-engine/stream/stream-list/stream-list.component.ts, web/src/app/services/rule-engine.service.ts
Signed-off-by: wshengqi@vmware.com <wshengqi@vmware.com>
=> update some contracts local

cmd/edgex-ui-server/res/configuration.toml, cmd/edgex-ui-server/res/docker/configuration.toml, go.mod, internal/component/mqtt.go, internal/component/websocket.go, internal/handler/export.go, internal/router.go
#275
update configuration file for docker and remove dead code
- [* ] No
- [* ] No
=> feat: issue-#275-17 update configuration file for docker and remove dead code

Dockerfile, Dockerfile.build, go.mod, internal/core/proxyhandler.go
#275
UI server update, golang version is changed from 1.5 to 1.6
- [* ] No
- [* ] No
=> Issue #275 20 UI server update

cmd/edgex-ui-server/res/configuration.toml, cmd/edgex-ui-server/res/docker/configuration.toml, web/src/app/contracts/v2/subscription.ts, web/src/app/notifications/notification/notification-list/notification-list.component.html, web/src/app/notifications/notification/notification-list/notification-list.component.ts, web/src/app/notifications/subscription/add-subscription/add-subscription.component.html, web/src/app/notifications/subscription/add-subscription/add-subscription.component.ts, web/src/app/notifications/subscription/edit-subscription/edit-subscription.component.html, web/src/app/notifications/subscription/edit-subscription/edit-subscription.component.ts, web/src/app/notifications/subscription/subscription-list/subscription-list.component.html, web/src/app/notifications/subscription/subscription-list/subscription-list.component.ts
#275 
notification update
- [*] No
- [ *] No
=> feat: Issue #275 21 notification update

web/src/app/contracts/v2/requests/operation-request.ts, web/src/app/contracts/v2/responses/health-response.ts, web/src/app/services/system-agent.service.ts, web/src/app/system-agent/config/config.component.html, web/src/app/system-agent/config/config.component.ts, web/src/app/system-agent/metrics/metrics.component.ts, web/src/app/system-agent/service-list/service-list.component.html, web/src/app/system-agent/service-list/service-list.component.ts
#275
system and notification update to match edgex v2 updates
- [ *] No
- [* ] No
=> feat: Issue #275 23 system update

web/src/app/contracts/v2/auto-event.ts, web/src/app/contracts/v2/common/base-response.ts, web/src/app/contracts/v2/device-service.ts, web/src/app/contracts/v2/device.ts, web/src/app/contracts/v2/interval-action.ts, web/src/app/contracts/v2/interval.ts, web/src/app/contracts/v2/notification.ts, web/src/app/contracts/v2/reading.ts, web/src/app/contracts/v2/responses/device-response.ts, web/src/app/contracts/v2/responses/device-service-response.ts, web/src/app/contracts/v2/responses/interval-action-response.ts, web/src/app/contracts/v2/responses/interval-response.ts, web/src/app/contracts/v2/responses/notification-response.ts, web/src/app/contracts/v2/responses/subscription-response.ts, web/src/app/contracts/v2/subscription.ts, web/src/app/scheduler/intervalaction/add-interval-action/add-interval-action.component.html, web/src/app/scheduler/intervalaction/add-interval-action/add-interval-action.component.ts, web/src/app/scheduler/intervalaction/edit-interval-action/edit-interval-action.component.html, web/src/app/scheduler/intervalaction/edit-interval-action/edit-interval-action.component.ts
scheduler update
#275 
scheduler update
- [* ] No
- [* ] No
=> feat: Issue #275 29 scheduler update

cmd/edgex-ui-server/res/configuration.toml, internal/handler/appservice.go, web/src/app/app-service/app-service-configurable/app-service-configurable.component.ts, web/src/app/app-service/app-service.component.html, web/src/app/app.component.html, web/src/app/rule-engine/rules/rules-list/rules-list.component.html, web/src/app/services/app-service.service.ts, web/src/app/services/rule-engine.service.ts
Signed-off-by: wshengqi@vmware.com <wshengqi@vmware.com>
#392
- fix wrong route path prefix of proxy to rule engine module of ui backend server
- fix wrong route path of app service module of ui backend server
- remove unused code or unimplemented features
- [ *] No
- [ *] No
=> feat: fix appservice model bugs

cmd/edgex-ui-server/res/docker/configuration.toml
#275
add the route path configuration of app service
- [* ] No
- [ *] No
=> feat: add the route path configuration of app service

Dockerfile, Makefile
1. if you clone the project and run `make docker`，it will report an error.because miss go.sum. you can repeat this.
2.  add docker tag suffix "dev"，other project has it.
=> fix: modify docker tag with dev

web/src/app/rule-engine/rules/add-rules/add-rules.component.html, web/src/app/rule-engine/rules/add-rules/add-rules.component.ts, web/src/app/rule-engine/rules/edit-rules/edit-rules.component.html, web/src/app/rule-engine/rules/edit-rules/edit-rules.component.ts, web/src/app/rule-engine/stream/edit-stream/edit-stream.component.ts, web/src/app/services/rule-engine.service.ts
Signed-off-by: wshengqi@vmware.com <wshengqi@vmware.com>
#401
- [* ] No
- [ *] No
=> feat: fix some bugs in UI

go.mod, internal/handler/registercenter.go, internal/router.go, web/src/app/app-service/add-app-service/add-app-service.component.html, web/src/app/app-service/add-app-service/add-app-service.component.ts, web/src/app/app-service/app-service-configurable/insecure-secrets/insecure-secrets.component.html, web/src/app/app-service/app-service-list/app-service-list.component.html, web/src/app/app-service/app-service-list/app-service-list.component.ts, web/src/app/contracts/v2/register-center/service-endpoint.ts, web/src/app/services/app-service.service.ts, web/src/app/services/system-agent.service.ts, web/src/app/system-agent/service-list/service-list.component.ts, web/src/app/system-agent/system-agent.component.ts
hard-code app service list and system service list
- Add backend support for achieving all app services and system services with new method.
- Update whole app service module, removed custom add new app function, and don't support delete app in the frontend any more.
- Update whole system agent module, using backend server to achieving all registered service from register center instead of hard-code.
- Other updates like remove dead code in system agent module, add associated contracts model and service.
- [* ] No
- [ *] No
Are there …
=> feat: System and appservice module updates

Dockerfile
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
=> ci: upgrade to alpine 3.14

README.md
close #473 
Signed-off-by: Huaqiao <huaqiaoz@vmware.com>
=> feat: update README.md and remove a number of broken links

snap/README.md
Signed-off-by: Mengyi <mengyi.wang@canonical.com>
=> docs(snap): remove replicated JWT instructions

bin/test-attribution-txt.sh, go.mod, snap/snapcraft.yaml
Changes related to Go 1.17 module changes
=> ci: gomod changes related for Go 1.17

Attribution.txt
Close #292 
- add attribution.txt file including all open source projects referenced by edgex-ui-go
=> feat: add all open source projects referenced by edgex-ui-go

.github/workflows/snap.yaml
The workflow added here will activate only after it has been merged into the main. In the meantime, https://github.com/MonicaisHer/edgex-ui-go/pull/2 that is against the fork can be taken as a reference.
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>
=> test(snap): add snap CI workflow

CHANGELOG.md
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
=> docs: add initial CHANGELOG and update it for Kamakura

web/src/app/metadata/device/add-device/add-device.component.html, web/src/app/metadata/device/add-device/add-device.component.ts
Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>
Closes #531 
> **NOTE: I did not commit the generated html and js files because I do not know if they would differ based on my setup or not. They will need to be generated.**
=> feat: add onvif and llrp protocol templates

.dockerignore, .gitignore, Dockerfile, Makefile, web/.dockerignore, web/Dockerfile, web/Makefile, web/README.md, web/angular.json, web/karma.conf.js, web/package-lock.json
The main goal of this PR is to have Jenkins run the Angular unit tests during the test stage, but getting that working is most of the way to making build/dev tasks work with Docker, so I've included those where it made sense:
- Added a Dockerfile and Makefile to the `web/` directory to do the following within a container:
- run the Angular unit tests
- build production versions of the site for each locale (output to `web/dist/`)
- run the dev server with hot-reloading
- Updated the `web/README.md` to fix the Angular version number and add info about the new Makefile/Dockerized build process
- Updated the root Makefile: 
- run the web unit tests upon `make test`
- add a `web` target to copy the production build to the `static` directory
- Configured karma so that unit tests can run in a …
=> build: automate angular test, build, and dev tasks

.blubracket/ignore.yaml
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
This is a pilot fix for https://github.com/edgexfoundry/edgex-go/issues/3881
Can only be tested via LFX Security dashboard.
=> ci: Add Blubracket ignore file to ignore generated files

Dockerfile
=> feat: copy Attribution.txt and LICENSE into Docker image

snap/snapcraft.yaml
- Remove unused packages
- Remove external metadata sourcing
=> refactor(snap): Update metadata sourcing, remove unused packages

web/src/app/guards/auth/login/login.component.html
<https://github.com/edgexfoundry/edgex-docs/pull/1029>
I have not tested this change at all, other then verifying the new URL.
=> feat: Update URL for authentication tokens for EdgeX 3.0

snap/snapcraft.yaml
Successfully passed the [edgex-snap-testing suite](https://github.com/canonical/edgex-snap-testing/tree/main/test/suites/ui) locally.
=> build(snap): Upgrade snap base to core22, upgrade go to 1.20

snap/snapcraft.yaml
* build(snap): Upgrade snap base to core22
---------
=> build(snap): Upgrade snap base to core22 (#599)

snap/local/bin/edgex-ui-wrapper.sh, snap/snapcraft.yaml
Fix for https://github.com/edgexfoundry/edgex-ui-go/pull/601#issuecomment-1534586534
=> refactor(snap): Switch to yaml config, upgrade go

snap/snapcraft.yaml
=> build(snap): Copy license and attribution

Makefile
Closes #580
Not tested at all; non-functional change.
=> build: Add -trimpath to improve binary reproducability of edgex-ui server

web/src/app/command/command-service-template/command-service-template.component.html, web/src/app/command/command-service-template/interfaces/command-service-info.ts, web/src/app/scheduler/intervalaction/add-interval-action/add-interval-action.component.html, web/src/app/scheduler/intervalaction/edit-interval-action/edit-interval-action.component.html, web/src/app/scheduler/intervalaction/edit-interval-action/edit-interval-action.component.ts
All the yes/no related to ds-returnevent and ds-pushevents has been replaced
Close: #626
-- No new UT are needed
-- The WEB has been deploy locally and the make test has been done.
-- Not needed
Running the web as the official doc said.
=> fix: Adaptation to V3 true/false for ds-pushevent ds-returnevent

web/src/app/metadata/provision-watcher/edit-provision-watcher/edit-provision-watcher.component.html, web/src/app/metadata/provision-watcher/edit-provision-watcher/edit-provision-watcher.component.ts, web/src/app/metadata/provision-watcher/provision-watcher-list/provision-watcher-list.component.html
=> fix: Fields for Provision Watcher Tab DTO

Attribution.txt
=> build: Update Attribution.txt for missing items

Makefile
=> ci: disable ARM Angular tests due to constant connection failures

CHANGELOG.md
=> docs: Update changelog for release 3.1
